{0}{500}Générique de début
{576}{648}Il y a un pré|dans mon univers idéal
{696}{744}où le vent fait danser|les branches d'un arbre
{744}{840}et projette des taches léopard|à la surface d'un étang.
{888}{936}L'arbre se dresse immense,
{936}{984}majestueux et solitaire,
{1008}{1056}tout en ombrageant le monde|qu'il domine.
{1344}{1416}Et c'est là,|dans le berceau de ce qui m'est cher,
{1440}{1488}que je garde mes souvenirs de toi.
{1536}{1608}Quand je serai figée|dans la boue du réel,
{1632}{1680}loin de tes yeux aimants,
{1728}{1752}je retournerai dans cet endroit,
{1800}{1824}fermerai les miens,
{1824}{1920}et trouverai du réconfort|dans le simple fait de te connaître.
{4416}{4440}Salut.
{4464}{4560}- T'as du sang sur ta chemise.|- J'étais au boulot.
{4584}{4632}Victime du jour ?
{4656}{4704}Moi, apparemment...
{4728}{4776}Du café ?
{4776}{4800}Volontiers.
{5520}{5568}Je dois aller à la Réserve demain.
{5568}{5640}Je pensais emmener Casey|voir tes parents.
{5736}{5784}Un yearling a été tué au pré.
{5784}{5808}J'y vais pour ça.
{5880}{5952}Ne quitte pas Casey des yeux.
{5976}{6048}Je le confierai à tes parents|pendant mes recherches.
{6048}{6072}Il fait trop froid...
{6072}{6120}Tu m'as comprise.
{6144}{6168}Oui.
{6240}{6264}Case !
{6288}{6312}- Papa !|- Viens, bonhomme.
{6312}{6336}J'arrive !
{6336}{6384}Faut y aller.
{6432}{6456}Tu vises quoi là ?
{6552}{6576}Allez, descends.
{6600}{6624}Excuse-moi, papa.
{6624}{6672}Quelle est la règle, bonhomme ?
{6672}{6744}Toujours faire comme s'il était chargé.
{6744}{6768}Compris ?
{6792}{6816}Allez, bonhomme.
{6816}{6864}Mets ça dans le pick-up.
{6888}{6912}Cours pas.
{7104}{7152}Je reviens lundi après-midi.
{7176}{7224}Sois prudente sur la route.
{7248}{7296}Les tempêtes, je connais.
{7392}{7416}C'est tout ?
{7608}{7632}Tiens, bonhomme.
{7704}{7752}C'est une ville bien, Wilma.
{7776}{7800}Avec de bonnes écoles.
{7824}{7896}Si on m'engage,|il faudra reparler de la pension.
{7944}{7992}La vie est plus chère à Jackson.
{8016}{8088}Si t'es engagée,|on réglera ce problème, t'inquiète.
{8136}{8160}Prends la Togwotee Pass.
{8160}{8208}Traverse pas Pinedale.
{8232}{8304}La tempête arrive du sud, alors...
{8304}{8376}Jamais je ne repasserai par Pinedale.
{8448}{8496}Pas question d'y retourner.
{8544}{8568}Bonne chance.
{8712}{8760}Vas-y, il a faim.
{8856}{8904}À table, les gars.
{9024}{9048}Ça va ?
{9048}{9072}Oui.
{9144}{9216}Repousse son museau|quand il se frotte contre toi.
{9288}{9336}Il a salopé ce chapeau.
{9336}{9384}Sa taille l'avantage sur moi.
{9384}{9408}Ah bon ?
{9432}{9456}On va régler ça.
{9504}{9552}Tu dois gagner son respect.
{9576}{9600}Sais-tu comment ?
{9624}{9648}En affirmant ta position.
{9672}{9696}Allez, en selle.
{9720}{9744}Comme je t'ai montré.
{9816}{9864}Qui est le plus grand là ?
{9888}{9960}Qui est le plus grand ?|Fais-le reculer.
{9960}{9984}En douceur.
{10008}{10032}Tant qu'il veut bien.
{10056}{10080}Emmène-le.
{10200}{10224}C'est bien.
{10224}{10296}Passe à côté de son fourrage.|Continue.
{10296}{10368}Voilà, montre qui est le chef.
{10368}{10416}Fais-le approcher latéralement.
{10536}{10560}Comme ça.
{10584}{10608}C'est ça, fiston.
{10704}{10728}Continue.
{10752}{10800}Fais-le reculer, il veut manger.
{10824}{10848}T'as vu ça ?
{10848}{10872}C'est bon, viens.
{10896}{10920}T'as vu ?
{10944}{10968}Beau travail. Amène-toi.
{10992}{11016}Flatte son museau.
{11016}{11112}Qu'il te sente, te respire|et fasse ta connaissance.
{11112}{11160}Il t'aimera à jamais.
{11352}{11376}Ça te plaît, fiston ?
{11400}{11448}C'est la méthode cow-boy, hein ?
{11472}{11496}Non, fiston.
{11520}{11544}Celle des Arapahoe.
{11640}{11760}VOUS ENTREZ DANS LA RÉSERVE|INDIENNE DE WIND RIVER
{12384}{12432}Mon petit-fils !
{12480}{12552}Grand-mère t'a préparé du pain frit.|Tu as mangé ?
{12552}{12600}- Que des oeufs.|- Va te régaler !
{12768}{12792}Ils sentent la tempête.
